# We download these files from the Broad GSEA page (https://www.gsea-msigdb.org/gsea/downloads.jsp#msigdb)
# The URLs provided need a bit of investigation with devtools to follow the redirection to the actual download URL, heheheheh.

version <- "2026.1"
options(timeout=3600)

output.tag <- "v1.1.0"
tax.ids <- c(Mm="10090", Hs="9606")

meta.fields <- list(
    # Copied from https://www.gsea-msigdb.org/gsea/msigdb/collections.jsp.
    Hs=list(
        h.all=list(
            title="MSigDB H: hallmark gene sets",
            description="Hallmark gene sets summarize and represent specific well-defined biological states or processes and display coherent expression. These gene sets were generated by a computational methodology based on identifying overlaps between gene sets in other MSigDB collections and retaining genes that display coordinate expression."
        ),
        c1.all=list(
            title="MSigDB C1: positional gene sets",
            description="Gene sets corresponding to human chromosome cytogenetic bands."
        ),
        c2.cgp=list(
            title="MSigDB C2: curated gene sets, CGP: chemical and genetic perturbations",
            description="Gene sets represent expression signatures of genetic and chemical perturbations. A number of these gene sets come in pairs: xxx_UP (and xxx_DN) gene set representing genes induced (and repressed) by the perturbation."
        ),
        c2.cp.pid=list(
            title="MSigDB C2: curated gene sets, CP: Canonical pathways, PID subset",
            description="Canonical Pathways gene sets derived from the PID pathway database."
        ),
        c2.cp.reactome=list(
            title="MSigDB C2: curated gene sets, CP: Canonical pathways, Reactome subset",
            description="Canonical Pathways gene sets derived from the Reactome pathway database."
        ),
        c2.cp.wikipathways=list(
            title="MSigDB C2: curated gene sets, CP: Canonical pathways, WikiPathways subset",
            description="Canonical Pathways gene sets derived from the WikiPathways pathway database."
        ),
        c3.mir.mirdb=list(
            title="MSigDB C3: regulatory target gene sets, MIR: microRNA targets, miRDB subset",
            description="Gene sets containing high-confidence gene-level predictions of human miRNA targets as catalogued by miRDB v6.0 algorithm (Chen and Wang, 2020)."
        ),
        c3.mir.mir_legacy=list(
            title="MSigDB C3: regulatory target gene sets, MIR: microRNA targets, MIR_LEGACY subset",
            description="Older gene sets that contain genes sharing putative target sites (seed matches) of human mature miRNA in their 3'-UTRs."
        ),
        c3.tft.gtrd=list(
            title="MSigDB C3: regulatory target gene sets, TFT: transcription factor targets, GTRD subset",
            description="Genes that share GTRD (Kolmykov et al. 2021) predicted transcription factor binding sites in the region -1000,+100 bp around the TSS for the indicated transcription factor."
        ),
        c3.tft.tft_legacy=list(
            title="MSigDB C3: regulatory target gene sets, TFT: transcription factor targets, TFT_LEGACY subset",
            description="Older gene sets that share upstream cis-regulatory motifs which can function as potential transcription factor binding sites. Based on work by Xie et al. 2005."
        ),
        c4.3ca=list(
            title="MSigDB C4: computational gene sets, 3CA: Curated Cancer Cell Atlas",
            description="Gene sets mined from the Curated Cancer Cell Atlas (3CA) metaprograms. These sets consist of genes that are coordinately upregulated in subpopulations of cells within 24 tumor types, covering both generic and lineage specifc cellular processes. The resource underlying this collection is described in Gavish et al. 2023."
        ),
        c4.cgn=list(
            title="MSigDB C4: computational gene sets, CGN: cancer gene neighborhoods",
            description="Gene sets defined by expression neighborhoods centered on 380 cancer-associated genes. This collection is described in Subramanian, Tamayo et al. 2005."
        ),
        c4.cm=list(
            title="MSigDB C4: computational gene sets, CM: cancer modules",
            descripton="Gene sets defined by Segal et al. 2004. Briefly, the authors compiled gene sets ('modules') from a variety of resources such as KEGG, GO, and others. By mining a large compendium of cancer-related microarray data, they identified 456 such modules as significantly changed in a variety of cancer conditions."
        ),
        c5.hpo=list(
            title="MSigDB C5: ontology gene sets, HPO: Human Phenotype Ontology",
            description="Gene sets derived from the Human Phenotype ontology."
        ),
        c6.all=list(
            title="MSigDB C6: oncogenic signature gene sets",
            description="Gene sets that represent signatures of cellular pathways which are often dis-regulated in cancer. The majority of signatures were generated directly from microarray data from NCBI GEO or from internal unpublished profiling experiments involving perturbation of known cancer genes."
        ),
        c7.immunesigdb=list(
            title="MSigDB C7: immunologic signature gene sets, ImmuneSigDB subset",
            description="Gene sets representing chemical and genetic perturbations of the immune system generated by manual curation of published studies in human and mouse immunology."
        ),
        c7.vax=list(
            title="MSigDB C7: immunologic signature gene sets, VAX: vaccine response gene sets",
            description="Gene sets curated by the Human Immunology Project Consortium (HIPC) describing human transcriptomic immune responses to vaccinations."
        ),
        c8.all=list(
            title="MSigDB C8: cell type signature gene sets",
            description="Gene sets that contain curated cluster markers for cell types identified in single-cell sequencing studies of human tissue."
        ),
        c9.all=list(
            title="MSigDB C9: computational perturbation signature gene sets gene sets",
            description="Gene sets that represent the coordinate transcriptional responses to expression of specific genes, as determined by computational analysis of DepMap CRISPR screen data and CCLE expression profiles."
        )
    ),

    # Copied from https://www.gsea-msigdb.org/gsea/msigdb/mouse/collections.jsp.
    Mm=list(
        mh.all=list(
            title="MSigDB MH: hallmark gene sets",
            description="Hallmark gene sets summarize and represent specific well-defined biological states or processes and display coherent expression. These gene sets were generated by a computational methodology based on identifying overlaps between gene sets in other MSigDB collections and retaining genes that display coordinate expression."
        ),
        m1.all=list(
            title="MSigDB M1: positional gene sets",
            description="Gene sets corresponding to mouse chromosome cytogenetic bands."
        ),
        m2.cgp=list(
            title="MSigDB M2: curated gene sets, CGP: chemical and genetic perturbations",
            description="Gene sets represent expression signatures of genetic and chemical perturbations. A number of these gene sets come in pairs: xxx_UP (and xxx_DN) gene set representing genes induced (and repressed) by the perturbation."
        ),
        m2.cp.reactome=list(
            title="MSigDB M2: curated gene sets, CP: Canonical pathways, Reactome subset",
            description="Canonical Pathways gene sets derived from the Reactome pathway database."
        ),
        m2.cp.wikipathways=list(
            title="MSigDB M2: curated gene sets, CP: Canonical pathways, WikiPathways subset",
            description="Canonical Pathways gene sets derived from the WikiPathways pathway database."
        ),
        m3.mirdb=list(
            title="MSigDB M3: regulatory target genes, miRDB gene sets",
            description="Gene sets containing high-confidence gene-level predictions of mouse miRNA targets as catalogued by miRDB v6.0 algorithm (Chen and Wang, 2020)."
        ),
        m3.gtrd=list(
            title="MSigDB M3: regulatory target gene sets, GTRD gene sets",
            description="Gene sets that contain genes annotated by the same ontology term. The M5 collection is divided into three subcollections derived from the Gene Ontology resource (GO) which contains BP, CC, and MF components."
        ),
        m5.mpt=list(
            title="MSigDB M5: ontology gene sets, MPT: tumor phenotype ontology",
            description="A subset of ontology terms from the Mammalian Phenotype Ontology database related to cancer specific phenotype terms."
        ),
        m7.all=list(
            title="MSigDB M7: immunologic signature gene sets",
            description="Gene sets that represent cell states and perturbations within the immune system."
        ),
        m8.all=list(
            title="MSigDB M8: cell type signature gene sets",
            description="Gene sets that contain curated cluster markers for cell types identified in single-cell sequencing studies of mouse tissue."
        )
    )
)

out.dir <- "_built"
unlink(out.dir, recursive=TRUE)
dir.create(out.dir, showWarnings=FALSE)

for (species in c("Hs", "Mm")) {
    raw.dir <- paste0("raw-", version, ".", species)

    if (!file.exists(raw.dir)) {
        dest <- paste0(species, ".zip")
        if (!file.exists(dest)) {
            url <- paste0("https://data.broadinstitute.org/gsea-msigdb/msigdb/release/", version, ".", species, "/msigdb_v", version, ".", species, "_files_to_download_locally.zip")
            if (download.file(url, destfile=dest) != 0) {
                stop("failed to download ", species, " MSigDB files")
            }
        }
        tmp <- tempfile(tmpdir=".")
        dir.create(tmp)
        unzip(dest, exdir=tmp)
        file.rename(tmp, raw.dir)
    }

    # Find the right subdirectory.
    raw.dir <- file.path(
        raw.dir,
        paste0("msigdb_v", version, ".", species, "_files_to_download_locally"),
        paste0("msigdb_v", version, ".", species, "_GMTs")
    )

    for (x in list.files(raw.dir, pattern="\\.entrez\\.gmt$")) {
        # Ignoring KEGG and Biocarta due to copyright issues.
        if (any(startsWith(
            x, 
            c(
                "c2.cp.kegg",
                "c2.cp.biocarta",
                "m2.cp.biocarta",
                "c2.all", # includes the above
                "m2.all", # includes the above
                paste0("c2.cp.v", version), # includes the above
                paste0("m2.cp.v", version) # includes the above
            )
        ))) {
            next
        }

        # Removing meta-collections that are redundant with other collections.
        if (any(startsWith(
            x,
            c(
                "c3.all", # redundant with other c3 entries. 
                "m3.all", # redundant with other m3 entries. 
                paste0("c3.mir.v", version), # redundant with the c3.mir.* entries. 
                paste0("c3.tft.v", version), # redundant with the c3.tft.* entries 
                "c4.all", # redundant with other c4 entries.
                "c5.all", # redundant with other c5 entries.
                "c5.go",  # redundant with our existing GO sets.
                "m5.all", # redundant with other m5 entries.
                "m5.go",  # reundant with our existing GO sets.
                "c7.all", # redundant with other c7 entries
                "msigdb"  # redundant with everything and also includes the difficult licenses.
            )
        ))) {
            next
        }

        pruned <- sub(paste0(".v", version, ".", species, ".entrez.gmt"), "", x, fixed=TRUE)
        current.meta <- meta.fields[[species]][[pruned]]
        stopifnot(!is.null(current.meta))

        contents <- readLines(file.path(raw.dir, x))
        handle <- gzfile(file.path(out.dir, paste0(pruned, ".gmt.gz")), open="wb")
        writeLines(contents, con=handle)
        close(handle)

        write(
            file=file.path(out.dir, paste0(pruned, ".json")),
            jsonlite::toJSON(
                list(
                    title=current.meta$title,
                    description=paste0(current.meta$description, " Part of MSigDB ", version, "."),
                    species=tax.ids[[species]],
                    maintainer="Aaron Lun",
                    id="entrez",
                    source=paste0("https://github.com/gesel-inc/feedstock/blob/msigdb-", output.tag, "/msigdb/build.R")
                ),
                auto_unbox=TRUE,
                pretty=4
            )
        )
    }
}

write(paste0("msigdb-", output.tag), file="_tag")
payload <- capture.output(print(sessionInfo()))
write(c("<details>", "<summary>Session information</summary>", "", "```", payload, "```", "</details>"), file="_session")
